name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Build extension # This build the extension for production
        run: npm run build
      - name: Zip extension # Archives the extension
        run: npm run build-zip
      - name: Save zip path to an env variable
        run: echo "::set-env name=RELEASE_EXTENSION_FILE::$(cd dist-zip && ls *.zip)"
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
        # Workaround to properly generate changelogs
        # I know this is a mess...
      - name: Generate changelogs
        run: git fetch --unshallow && git checkout HEAD^ && git clone https://github.com/MihaiVoinea/generate-changelog.git && npm i -g ./generate-changelog && generate-changelog -s v${{ steps.package-version.outputs.version }}
      - name: Read Release Notes
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: "./dist-zip/${{ env.RELEASE_EXTENSION_FILE }}"
          asset_name: ${{ env.RELEASE_EXTENSION_FILE }}
          asset_content_type: application/zip
